# Generated by Django 5.1.4 on 2025-03-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0004_alter_contact_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="desc",
            field=models.TextField(blank=True, null=True),
        ),
    ]
